### ISSUE TITLE
Update readme to have info regarding scrollTarget prop

### ISSUE THREAD

**Issue by kosanna** [jossmac/react-scrolllock#10]
Today I got a little bit of a pain debugging why touch scroll does not work within some overflowing inner components on the page that I want be scrollable when scroll is locked with presence of Scrollock.

Then I've found that I can pass a scrollTarget={myScrollableContainer} prop to Scrolllock to fix it. However that was through reading actual source code, not the README file, so probably it could be great if it's updated.

**Comment by emphaticsunshine** [comment]
I also learned it hard way today. How did you end up passing ref for `scrollableContainer`?

**Comment by evan-dennington-ck** [comment]
@kosanna could you possibly share your solution for the scrollTarget? Having some issues getting it to work on my end.

**Comment by jossmac** [comment]
@evan-dennington-ck I've updated the README.md but here's an example implementation:

```jsx
import ScrollLock from 'react-scrolllock';

class Modal extends Component {
  getScrollTarget = (ref) => { this.scrollTarget = ref; }
  render() {
    return (
      <div>
        <div ref={this.getScrollTarget} style={{ overflowY: 'auto', maxHeight: 400 }}>
          ...
        </div>
        <ScrollLock touchScrollTarget={this.scrollTarget} />
      </div>
    );
  }
}
```
