### ISSUE TITLE
css transform: translateX not working with react-scrolllock

### ISSUE THREAD

**Issue by stevencmh** [jossmac/react-scrolllock#107]
Hi,

This is great but is it possible to use along with translateX?

I have a mobile menu that slides in from the right however that no longer works when using react-scrolllock. Instead it just immediately appears when toggling the menu.

Thanks!

**Comment by jossmac** [comment]
Can you [provide a reproduction](https://codesandbox.io/)?

**Comment by stevencmh** [comment]
Hi, in the end I had to use a time out to delay the scroll lock and let the transition finish.
