### ISSUE TITLE
Support for react v18

### ISSUE THREAD

**Issue by AndrewKiri** [jossmac/react-scrolllock#113]
It seems something needs to be done there to allow for installing while having react at version 18. 
<img width="643" alt="Screenshot 2023-02-18 at 22 16 44" src="https://user-images.githubusercontent.com/13384229/219899868-902f0d94-5551-4827-9d05-75ea32b3ca6f.png">

**Comment by diogocnunes92** [comment]
Any news on this?

**Comment by jossmac** [comment]
Sorry folks, this project is no longer maintained. Consider an alternative like [react-remove-scroll](https://www.npmjs.com/package/react-remove-scroll).
