### ISSUE TITLE
React v15.5.0 Deprecation Warnings - React.PropTypes and React.createClass

### ISSUE THREAD

**Issue by bhtabor** [jossmac/react-scrolllock#3]
src/ScrollLock.js needs a simple fix according to https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by rafi** [comment]
(Using v1.0.6) In the console:
> Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. \@ [ScrollLock.js line 12](https://github.com/jossmac/react-scrolllock/blob/master/src/ScrollLock.js#L12)

**Comment by adamgedney** [comment]
Can we get a new npm release fixing the issue @rafi is referring to?

**Comment by kachkaev** [comment]
Also seeing a warning because of this. This also prevents https://github.com/jossmac/react-images/issues/132 from being fixed in full.

**Comment by kachkaev** [comment]
@jossmac could you please consider https://github.com/jossmac/react-scrolllock/pull/5?

**Comment by kachkaev** [comment]
ping @jossmac :–)

**Comment by damiangreen** [comment]
ping @jossmac :–)

**Comment by khakulov** [comment]
ping @jossmac :–)

**Comment by jorrit** [comment]
I believe this issue is fixed because PR #5 was committed.

**Comment by jossmac** [comment]
Resolved by https://github.com/jossmac/react-scrolllock/pull/5

**Comment by kachkaev** [comment]
Awesome, many thanks @jossmac! When about are you planning to cut a new release?

**Comment by jossmac** [comment]
@kachkaev v1.0.8 is on npm 🙂
