### ISSUE TITLE
findDOMNode is Deprecated

### ISSUE THREAD

**Issue by ssylvia** [jossmac/react-scrolllock#41]
Looks like this library uses `findDOMNode` internally.

This is now deprecated in React and throws a warning when running in StrictMode: https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage

**Comment by yankuanz** [comment]
The dependency `react-node-resolver` is using `findDOMNode`: 

https://github.com/jossmac/react-scrolllock/blob/master/src/TouchScrollable.js#L4

https://github.com/jossmac/react-node-resolver/blob/master/src/NodeResolver.js#L4

Just created an issue in that repo.

**Comment by jossmac** [comment]
Changes described in #52 available in `5.0.0`
