### ISSUE TITLE
Can we swipe the images 

### ISSUE THREAD

**Issue by Dlohani1** [jossmac/react-scrolllock#43]

**Comment by Dlohani1** [comment]
Cannot read property '0' of undefined
    at Carousel.getViewData 
After updating the packaged.

**Comment by Dlohani1** [comment]
@jossmac @neptunian help me to understand how to implement custom view inside carousel in  updated package in v1.

**Comment by jossmac** [comment]
Wrong repo mate, try https://github.com/jossmac/react-images
