### ISSUE TITLE
Page scrolls to the top when scrollLock is active

### ISSUE THREAD

**Issue by joebentaylor** [jossmac/react-scrolllock#44]
For some reason the body locks as intended. But the page scrolls to the top and locks, not like in the demo where the body locks wherever the current scroll position is.

Im using the Gatsby frontend framework, has anybody experienced this issue?

**Comment by oliviergenevest** [comment]
same issue here :  the page scrolls to the top and locks , using gatsby js. Did you find a solution ?

**Comment by rista404** [comment]
I experienced the same issue and the problem was that `html` had `overflow-y: scroll`. Disabling that fixed the issue, hope it helps.

**Comment by jossmac** [comment]
This seems to be a Gatsby specific issue. Perhaps they provide some sort of scroll restoration out-of-the-box? Would be great to get some more details.

**Comment by jossmac** [comment]
Thanks @rista404
