### ISSUE TITLE
TouchScrollable event listener error

### ISSUE THREAD

**Issue by aliceclv** [jossmac/react-scrolllock#66]
Hi!
I am using the `5.0.0` version but getting an error:
```
Uncaught TypeError: Cannot read property 'addEventListener' of undefined
  at TouchScrollable.componentDidMount (TouchScrollable.js:50)
```
This code seems to be breaking:
```js
  _createClass(TouchScrollable, [{
    key: 'componentDidMount',
    value: function componentDidMount() {
      if (!_exenv.canUseEventListeners) return;
     // Breaking line
      this.scrollableArea.addEventListener('touchstart', _utils.preventInertiaScroll, _utils.listenerOptions);
      this.scrollableArea.addEventListener('touchmove', _utils.allowTouchMove, _utils.listenerOptions);
    }
```
This was my original piece of code. Every time `isOpen` was set to true, I was getting the error above.
```js
import ScrollLock from 'react-scrolllock';

function Sidebar(...) {
   // ...
   return (
    <MobileSidebar>
      <ScrollLock isActive={isOpen}>{children}</ScrollLock>
    <MobileSidebar/>
    );
}
```
Am I doing something wrong here? 🤔
I fixed it the following way, but was wondering if I was misusing it.
```js
import ScrollLock from 'react-scrolllock';

function Sidebar(...) {
   // ...
   return (
    <MobileSidebar>
      {isOpen && <ScrollLock />}
      {children}
    <MobileSidebar/>
    );
}
```
Thanks a lot 🙏 !

**Comment by jossmac** [comment]
When children are passed to the scroll lock it's expecting a single element for touch-scroll handling. Please see the [usage documentation](https://github.com/jossmac/react-scrolllock#usage).

**Comment by avand** [comment]
I'm running into this issue as well. I'm not sure what you mean by "expecting a single element for touch-scroll handling." Would a React component constitute a "single element?" Because that's how I'm using it now and I'm getting this error:

```
    <ScrollLock isActive={overlay} />
    <TouchScrollable>
      {children}
    </TouchScrollable>
```
