### ISSUE TITLE
Content shifting when opening and closing lightbox

### ISSUE THREAD

**Issue by neptunian** [jossmac/react-scrolllock#7]
Due to this recent commit:
https://github.com/jossmac/react-scrolllock/commit/99f54ed9e8e04611e0d981d733affc8aa7c204f1

The defaultProps prop is being defined incorrectly and therefore 
`if (this.props.preventContentJumping) {`
will evaluate to undefined/false and content will shift instead of defaulting to not shifting.

**Comment by neptunian** [comment]
See  pull request https://github.com/jossmac/react-scrolllock/pull/8

**Comment by jorrit** [comment]
A work around is to set the prop explicitly.

**Comment by neptunian** [comment]
@jorrit yes but would require the user to modify the Lightbox.js source file.

**Comment by neptunian** [comment]
@jossmac can we get this published on npm please :)

**Comment by gtwilliams03** [comment]
I have this same issue.  Layout in react-photo-gallery looks great on load (I am also using a Lightbox).  Clicking on an image opens the Lightbox and I can see the layout through the overlay still looking nice.  Then I close the Lightbox and the scroll bar breaks the layout and the images wrap to the next row. If I reopen the Lightbox, the layout in react-photo-gallery looks normal again.

**Comment by gtwilliams03** [comment]
OK - I had a container div with a percentage width `<div style={{ width: '96%' }}>` and the disappearance and reappearance of the scroll bar was breaking the layout.  I changed the `width: '96%'` to `width: '96vw'` and the layout stays intact.  Passing this along in case it helps someone.
